## Create a new user
POST http://localhost:4000/users
Content-Type: application/json

{
  "username": "Sabina",
  "password": "password"
}

###

## Get list of users
GET http://localhost:4000/users

#######################################################
## Refresh tokens carry the information necessary to get a new access token. 
## In other words, whenever an access token is required to access a specific resource, 
## a client may use a refresh token to get a new access token issued by the authentication server.

# Create user-specific refreshToken from username (only done once to get refreshToken 
#    --> store in database with username)
#    --> this will be the raw email + password (not hash) 
# USE .env (super secret server only)
# SAVE GENERATED REFRESHTOKEN IN CLIENT AND DATABASE
POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Sabina", 
  "password": "password"
}

###

# Function for generating accessToken from given refreshToken
# USE CLIENT REFRESHTOKEN + .env (super secret server only), CHECK THAT IT EXISTS IN DATABASE
# SAVE GENERATED ACCESSTOKEN IN CLIENT AND DATABASE
POST http://localhost:4000/token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhYmluYSIsImhhc2hlZFBhc3N3b3JkIjoiJDJiJDEwJC5PNnNVaGFKaWdGZ25JcTRVcW1sSWV4TnkubloxdndlVHhDZld0cjRvSlU1dUh5dktWUkh5IiwiaWF0IjoxNjA2NzAyMDQ0fQ.TsmqpY8VVaJa-HKUK2N2LoEM4cbII8zu7kV5MFDuoMk"
}

###

# Function to delete refreshToken from the database
DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhYmluYSIsImhhc2hlZFBhc3N3b3JkIjoiJDJiJDEwJC5PNnNVaGFKaWdGZ25JcTRVcW1sSWV4TnkubloxdndlVHhDZld0cjRvSlU1dUh5dktWUkh5IiwiaWF0IjoxNjA2NzAyMDQ0fQ.TsmqpY8VVaJa-HKUK2N2LoEM4cbII8zu7kV5MFDuoMk"
}

###

# Function to get user's posts using accessToken (only valid for 15 sec)
# USE CLIENT ACCESSTOKEN FOR REQUESTS
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhYmluYSIsImlhdCI6MTYwNjcwMjA2OSwiZXhwIjoxNjA2NzAyMDg0fQ.cmZIxKyL568xqDyEl9K3colwYz7IoqQhfRZH5nQNxfY